### ISSUE TITLE
No notifications on Mac OSX 12.5

### ISSUE THREAD

**Issue by portalzine** [seird/gotify-tray#7]
No notifications on Mac OSX 12.5.
The tray application is launching and communication with the server works aswell.
New messages are listed in the message window.

I am working with terminal-notifier for other stuff, which works perfectly.

Thanks
Alex

**Comment by seird** [comment]
I've only tested the macOS Monterey build in a virtual machine. In order to receive notifications I had to first enable them in the system preferences.

`System Preferences -> Notifications` (https://support.apple.com/en-us/HT204079)

I'm not familiar with terminal-notifier, but it seems it only runs inside the terminal? In that case it's probably allowed to send notifications by default because it's a system application.

I will take a closer look later.

**Comment by portalzine** [comment]
The Gotify-Tray is not even listed in the notifications center, that is what I checked first.
The terminal-notifier was registered on first execution. ([github](https://github.com/julienXX/terminal-notifier))

But other than that, thanks for the app :) Great help getting Gotify integrated systemwide !

**Comment by seird** [comment]
It seems to work as intended for me on version 12.5.1. I get the following pop-up when it receives a notification for the first time, which then sends me to the system preferences:

![popup](https://user-images.githubusercontent.com/55763130/185756978-db56ed95-6e5c-4ef0-b27b-f2a88b526c84.png)


Is it possible you have the main window open and in focus as the new messages are coming in? Whenever the main window is in focus, there won't be any pop-up notifications (by design).

I assume you installed it from the disk image in releases or are you using pip or running from source?

Is the tray icon itself visible? There is some relevant logging if you set it to level "WARNING" under `Settings->Advanced->Logging` that will create a log entry if the system doesn't support notifications or tray icons, although that sounds highly unlikely to me..

**Comment by portalzine** [comment]
Was running it from source. Just testdrived the precompiled DMG, same thing.
Window was closed both times. Not even getting the notification request and the entry.
Strange. The system allows tray icons and notifications, have multiple other cli apps working and sending notifications from python.

Update: Did a complete reboot to make sure. But same thing. Also removed other notification settings, to make sure nothing is broken. Log is clean no error!

**Comment by seird** [comment]
Strange... the only other thing I can think of at the moment is that the notifications that are being sent might have a priority lower than 5?

**Comment by seird** [comment]
I can add some more logging in the new message callback.. if you're still interested in testing at least

**Comment by portalzine** [comment]
Just did a complete cleanup of all preferences and started clean. Same thing.
Sure, happy to testdrive anything you throw at me ;) (almost anything ...)

**Comment by portalzine** [comment]
You are right, the priority was 4 on those test messages :)
All working now, sorry and thanks.

**Comment by seird** [comment]
I didn't make that cutoff clear enough I guess, but if I remember correctly it's the default in the android app as well.. Glad it's working 😃
